CREATE TABLE Payment (
    PaymentID int NOT NULL AUTO_INCREMENT,
    FOREIGN KEY (BookingID) REFERENCES Booking(BookingID),
    FOREIGN KEY (CardID) REFERENCES CreditCard(CardID)
);
CREATE TABLE CreditCard (
    CardID int NOT NULL AUTO_INCREMENT,
    Card_Number int NOT NULL,
    CVC int NOT NULL,
    Expiry date
);

CREATE TABLE Enquiry (
    EnquiryID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Question VARCHAR (150),
    Reply VARCHAR (150),
    Resolved BOOLEAN,
    UserID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES USER(ID)
);

CREATE TABLE RoomType (
    RoomTypeID INT NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 10000, INCREMENT BY 1),
    CostPerDay DOUBLE NOT NULL,
    NumBeds INT NOT NULL,
    Suite VARCHAR(150),
    Description VARCHAR(255),
    PRIMARY KEY(RoomTypeID)
);
